name: msrv

on:
  pull_request:
  push:
    tags:
    branches:
      - master

permissions: {}

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        crate-path:
          - web_push
          - ece
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false
      - run: rustup toolchain install stable
      - run: cargo install cargo-msrv
      - run: cargo msrv --path ${{ matrix.crate-path }} verify
